version: 0.0
os: linux
files:
  - source: build/index.html
    destination: /var/www/html/
  - source: build/service-worker.js
    destination: /var/www/html/  
  - source: build/asset-manifest.json
    destination: /var/www/html/  
  - source: build/favicon.ico
    destination: /var/www/html/  
  - source: build/static/js/main.42ee9d36.js
    destination: /var/www/html/static/js/    
  - source: build/static/css/main.6d9df600.css
    destination: /var/www/html/static/css/   
  - source: build/images/01.jpg
    destination: /var/www/html/images/     
  - source: build/images/02.jpg
    destination: /var/www/html/images/   
  - source: build/images/03.jpg
    destination: /var/www/html/images/   
  - source: build/images/04.jpg
    destination: /var/www/html/images/   
  - source: build/images/05.jpg
    destination: /var/www/html/images/   
  - source: build/images/06.jpg
    destination: /var/www/html/images/    
hooks:
  BeforeInstall:
    - location: scripts/install
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy
      timeout: 300
      runas: root  
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
