version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - yum -y update
      - yum install curl -y
      - yum install git -y
  build:
    commands:
      - curl -sL https://rpm.nodesource.com/setup_14.x | bash -
      - yum install -y nodejs
      - node --version
      - git clone https://github.com/Monimoralesa/reactjs-shopping-cart.git
      - cd reactjs-shopping-cart
      - npm install
      - npm run build
      - tar cfv build.tar build/ scripts/install scripts/start_server scripts/stop_server appspec.yml
      - ls -ltar
      - pwd
  post_build:
    commands:
      - aws s3 cp build.tar s3://shopping-cart-jmonicam-cr3
artifacts:
  files:
    - '*/build/**'
    - '*/scripts/**' 
    - '*/appspec.yml'
    - '*/build/static/js/**'
    - '*/build/static/css/**'
    - '*/build/images/**'
  base-directory: $CODEBUILD_SRC_DIR
